tcc:
  coordinator:
    url: http://localhost:9090/coordinator
  transaction:
    timeoutInMs: 30000
  participant:
    orderService: http://localhost:8084/order/tcc/%s
    inventoryService: http://localhost:8083/inventory/tcc/%s