spring:
  application:
    name: order-service
  datasource:
    order:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:33206/tcc_order?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: _hx7h82gfc28c250n

server:
  port: 8084