server:
  port: 8083
spring:
  application:
    name: inventory-service
  datasource:
    inventory:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:33206/tcc_inventory?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: _hx7h82gfc28c250n